<?php require_once '../templates/includes/header.inc.phtml'; ?>
<?php require_once '../templates/includes/aside.inc.phtml'; ?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Dashboard</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Création viennoiserie</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <!-- Main row -->
            <div class="row">
                <!-- Left col -->
                <section class="col-lg-12 connectedSortable">
                    <!-- Default box -->
                    <!-- Form -->
                    <?php
                    if($_session->hasFlash('createPastry')):
                        $status = $_session->getFlash('createPastry');

                        if($status === 'success'): ?>
                            <div class="alert alert-success alert-dismissible">
                                Nouvelle viennoiserie correctement ajoutée !
                                <button type="button" class="close" data-dismiss="alert">
                                    &times;
                                </button>
                            </div>
                        <?php   else: ?>
                            <div class="alert alert-danger alert-dismissible">
                                <?php echo $status; ?>
                                <button type="button" class="close" data-dismiss="alert">
                                    &times;
                                </button>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Création d'une nouvelle viennoiserie</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="post" action="<?php echo $_url('admin_create_pastry'); ?>">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">Nom</label>
                                    <input type="text" class="form-control" id="name" name="name" placeholder="Nom">
                                </div>
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="available" name="available" value="true" />
                                    <label class="form-check-label" for="available">Disponibilité</label>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <?php echo $_csrf('createPastry'); ?>
                                <button type="submit" class="btn btn-primary">Créer</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </section>
                <!-- /.Left col -->
                <!-- right col -->
            </div>
            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<?php require_once '../templates/includes/footer.inc.phtml'; ?>
