    <?php require_once '../templates/includes/header.inc.phtml'; ?>
    <!-- Main Sidebar Container -->
    <?php require_once '../templates/includes/aside.inc.phtml'; ?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Liste des étudiants</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Étudiants</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                    <section class="col-lg-12 connectedSortable">
                        <!-- Bordered Table -->
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Étudiants</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>Login</th>
                                            <th>Alias</th>
                                            <th>Pâtisserie par défaut</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($students as $student): ?>
                                            <tr>
                                                <td><?php echo $student->getId(); ?></td>
                                                <td><?php echo $student->getLogin(); ?></td>
                                                <td><?php echo $student->getAlias(); ?></td>
                                                <td>
                                                    <?php
                                                        if($student->getDefaultPastry() !== null)
                                                            echo $student->getDefaultPastry()->getName();
                                                        else
                                                            echo 'Indéfinis';
                                                    ?>
                                                </td>
                                                <td>
                                                    <a href="<?php echo $_url('admin_modify_student', ['id' => $student->getId()]); ?>">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                            <div class="card-footer">
                                <a href="<?php echo $_url('admin_create_student'); ?>"><button type="button" class="btn btn-primary">Nouvel étudiant</button</a>
                            </div>
                        </div>
                        <!-- /.card -->
                    </section>
                    <!-- /.Left col -->
                    <!-- right col -->
                </div>
                <!-- /.row (main row) -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

    <?php require_once '../templates/includes/footer.inc.phtml'; ?>
