    <?php require_once '../templates/includes/header.inc.phtml'; ?>
    <!-- Main Sidebar Container -->
    <?php require_once '../templates/includes/aside.inc.phtml'; ?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Liste des viennoiseries</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Viennoiseries</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                    <section class="col-lg-12 connectedSortable">
                        <!-- Bordered Table -->
                        <?php if($_session->hasFlash('modifyPastry')): ?>
                            <?php $result = $_session->getFlash('modifyPastry'); ?>
                            <?php if($result === 'success'): ?>
                                <div class="alert alert-success alert-dismissible">
                                    Viennoiserie correctement mise à jour !
                                    <button type="button" class="close" data-dismiss="alert">
                                        &times;
                                    </button>
                                </div>
                            <?php else: ?>
                                <div class="alert alert-info alert-dismissible">
                                    Aucun champs n'a été modifié.
                                    <button type="button" class="close" data-dismiss="alert">
                                        &times;
                                    </button>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>

                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Viennoiseries</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>Nom</th>
                                            <th>Disponible</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($pastries as $pastry): ?>
                                            <tr>
                                                <td><?php echo $pastry->getId(); ?></td>
                                                <td><?php echo $pastry->getName(); ?></td>
                                                <td>
                                                    <?php $available = ($pastry->getIsAvailable() === true) ? 'fa-check text-success' : 'fa-times text-danger'; ?>
                                                    <i class="fa <?php echo $available; ?>"></i>
                                                </td>
                                                <td>
                                                    <a href="<?php echo $_url('admin_modify_pastry', ['id' => $pastry->getId()]); ?>">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                            <div class="card-footer">
                                <a href="<?php echo $_url('admin_create_pastry'); ?>"><button type="button" class="btn btn-primary">Nouvelle viennoiserie</button</a>
                            </div>
                        </div>
                        <!-- /.card -->
                    </section>
                    <!-- /.Left col -->
                    <!-- right col -->
                </div>
                <!-- /.row (main row) -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

    <?php require_once '../templates/includes/footer.inc.phtml'; ?>
