<?php require_once '../templates/includes/header.inc.phtml'; ?>
<!-- Main Sidebar Container -->
<?php require_once '../templates/includes/aside.inc.phtml'; ?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Mise à jour des droits</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item">Étudiants</li>
                        <li class="breadcrumb-item active">Droits</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Main row -->
            <div class="row">
                <!-- Left col -->
                <section class="col-lg-12 connectedSortable">
                    <!-- Bordered Table -->
                    <?php if($_session->getFlash('rightUpdateSuccess') === true): ?>
                        <div class="alert alert-success">
                            Droits correctement mis à jour !
                        </div>
                    <?php endif; ?>
                    <form action="<?php echo $_url('admin_update_rights'); ?>" method="post">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Droits des étudiants</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th style="width: 10px">#</th>
                                        <th>Login</th>
                                        <th>Alias</th>
                                        <th>Droit</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($studentsAndRights as $line): ?>
                                        <?php $student = $line['student']; ?>
                                        <?php $right = $line['right']; ?>
                                        <tr>
                                            <td><?php echo $student->getId(); ?></td>
                                            <td><?php echo $student->getLogin(); ?></td>
                                            <td><?php echo $student->getAlias(); ?></td>
                                            <td>
                                                <select name="rights[<?php echo $student->getId(); ?>]">
                                                    <?php foreach ($roles as $id => $role): ?>
                                                        <option <?php echo ($right->getRoleId() === $id ? 'selected' : ''); ?> value="<?php echo $id ?>">
                                                            <?php echo (!empty($role) ? $role : 'Utilisateur lambda'); ?>
                                                        </option>
                                                    <?php endforeach; ?>
                                                </select>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                            <div class="card-footer">
                                <?php echo $_csrf('adminUpdateRights'); ?>
                                <button type="submit" class="btn btn-primary">Mise à jour des droits</button>
                            </div>
                        </div>
                    </form>
                    <!-- /.card -->
                </section>
                <!-- /.Left col -->
                <!-- right col -->
            </div>
            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

<?php require_once '../templates/includes/footer.inc.phtml'; ?>
