<?php require_once '../templates/includes/header.inc.phtml'; ?>
<?php require_once '../templates/includes/aside.inc.phtml'; ?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Page d'erreur 400</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Page d'erreur 400</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="error-page">
                <h2 class="headline text-warning"> 400</h2>

                <div class="error-content">
                    <h3><i class="fas fa-exclamation-triangle text-warning"></i> Oups ! Une erreur est survenue.</h3>

                    <p>
                        Une erreur est survenue lors de la validation du formulaire.
                        Vous pouvez <a href="<?php echo $_url('index'); ?>">retourner à l'accueil</a>.
                    </p>
                </div>
                <!-- /.error-content -->
            </div>
            <!-- /.error-page -->
        </section>
        <!-- /.content -->
    </div>

<?php require_once '../templates/includes/footer.inc.phtml'; ?>