<?php require_once '../templates/includes/header.inc.phtml'; ?>
<?php require_once '../templates/includes/aside.inc.phtml'; ?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Dashboard</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Modification</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <!-- Main row -->
            <div class="row">
                <!-- Left col -->
                <section class="col-lg-12 connectedSortable">
                    <!-- Default box -->
                    <!-- Form -->
                    <?php
                    if($_session->hasFlash('newCroissantage')):
                        $status = $_session->getFlash('newCroissantage');

                        if($status === 'success'): ?>
                            <div class="alert alert-success">
                                Nouveau croissantage correctement ajouté !
                            </div>
                        <?php   else: ?>
                            <div class="alert alert-danger">
                                <?php echo $status; ?>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>

                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Nouveau croissantage !</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="post" action="<?php echo $_url('new_croissantage'); ?>">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="croissanted">Personne croissantée</label>
                                    <select class="form-control" id="croissanted" name="croissanted">
                                        <?php foreach ($students as $student): ?>
                                            <option value="<?php echo $student->getId(); ?>">
                                                <?php echo $student->getAlias(); ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="croissanter">Croissanteur</label>
                                    <select class="form-control" id="croissanter" name="croissanter">
                                        <?php foreach ($students as $student): ?>
                                            <option value="<?php echo $student->getId(); ?>">
                                                <?php echo $student->getAlias(); ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="date">Date de croissantage</label>
                                    <input type="datetime-local" class="form-control" id="date" name="date" />
                                </div>
                                <div class="form-group">
                                    <label for="dateCommand">Date de commande</label>
                                    <input type="datetime-local" class="form-control" id="dateCommand" name="dateCommand" />
                                </div>
                                <div class="form-group">
                                    <label for="dateDelivery">Date de livraison</label>
                                    <input type="date" class="form-control" id="dateDelivery" name="dateDelivery" />
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <?php echo $_csrf('newCroissantage'); ?>
                                <button type="submit" class="btn btn-primary">Ajouter</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </section>
                <!-- /.Left col -->
                <!-- right col -->
            </div>
            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

<?php require_once '../templates/includes/footer.inc.phtml'; ?>
