<?php require_once '../templates/includes/header.inc.phtml'; ?>
<?php require_once '../templates/includes/aside.inc.phtml'; ?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Dashboard</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Vote</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- /.row -->
            <!-- Main row -->
            <div class="row">
                <!-- Left col -->
                <section class="col-lg-12 connectedSortable">
                    <!-- Default box -->
                    <!-- Form -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Vote pour croissantage</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form role="form" method="post" action="<?php echo $_url('vote_croissantage', ['id' => $croissantageId]); ?>">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="pastry">Que prendrez-vous ?</label>
                                    <select class="form-control" id="pastry" name="pastry">
                                        <option value="-1">Aucune</option>
                                        <?php $default = ($student->getDefaultPastry() !== null) ? $student->getDefaultPastry()->getId() : false; ?>
                                        <?php foreach ($pastries as $pastry): ?>
                                            <option <?php echo (($pastry->getId() === $default) ? 'selected' : ''); ?> value="<?php echo $pastry->getId(); ?>"><?php echo $pastry->getName(); ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <?php echo $_csrf('voteCroissantage'); ?>
                                <button type="submit" class="btn btn-primary">Voter</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </section>
                <!-- /.Left col -->
                <!-- right col -->
            </div>
            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

<?php require_once '../templates/includes/footer.inc.phtml'; ?>
